Add integration test for variadic params

diff --git a/ttps/examples/variadic-params/delta.yaml b/ttps/examples/variadic-params/delta.yaml
--- a/ttps/examples/variadic-params/delta.yaml
+++ b/ttps/examples/variadic-params/delta.yaml
@@ -1,24 +1,10 @@
 ---
-name: delta
-description: Login with a Meta account that has the delta check triggered.
+name: paramtest
+description: Test variadiac parameter handling
 steps:
-  - name: "delta"
+  - name: "paramtest"
     inline: |
       set -e
-
-      ### Set default headless value if one isn't provided ###
-      headless="{{headless}}"
-      # Set default headless value if one isn't provided
-      if [[ $headless == 'false' ]]; then
-          headless=false
-      else
-          headless=true
-      fi
-
-      keeperRecord="$(echo {{keeperRecord}} | tr -d '\n\t\r')"
-      if [[ "{{keeperRecord}}" == *'{{'* ]]; then
-        keeperRecord=""
-      fi
 
       user="$(echo {{user}} | tr -d '\n\t\r')"
       if [[ "{{user}}" == *'{{'* ]]; then
@@ -35,14 +21,12 @@ steps:
         token=""
       fi
 
-      if [[ -z "$keeperRecord" ]] && [[ (-z "$user") || (-z "$password") ]]; then
-          echo "Error: Either keeperRecord or both user and password must have a value."
+      if [[ (-z "$user") || (-z "$password") ]]; then
+          echo "Error: Both user and password must have a value."
           exit 1
       fi
 
       go run delta.go \
         --user $user \
         --password $password \
-        --kr "$keeperRecord" \
-        --token "$token" \
-        --headless=$headless
+        --token "$token"
